# nginx proxy address - http://172.17.0.1:60129

name: checkmk
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: checkmk/check-mk-raw:latest
    container_name: checkmk-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      - CMK_SITE_ID=cmk
      - CMK_LIVESTATUS_TCP=on
      - TZ=${TZ:-America/New_York}
      - CMK_PASSWORD=${APP_TEMP_PASS:-u86ydJk3WmCfpODZ}
      - MAIL_RELAY_HOST=${EMAIL_SERVER_HOST:-172.17.0.1}
    ports:
      - '162:162'
      - '514:514'
      - '4317:4317'
      - '4318:4318'
      - '6558:6558'
      - '6559:6559'
      - '60128:8000'
      - '172.17.0.1:60129:5000/tcp'
    ulimits:
      nofile: 1024
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './rootfs/data/checkmk:/omd/sites'
    tmpfs:
      - '/opt/omd/sites/cmk/tmp:uid=1000,gid=1000'
    networks:
      - checkmk

networks:
  checkmk:
    name: checkmk
    external: false
